---
title: "Class 18"
author: "Katelyn Wei (PID: A16682595)"
format: pdf
---

# Downstream Analysis

I downloaded the tximport package. The directories containing the callisto outputs have been added to my computer.
```{r}
library(tximport)
library(rhdf5)
```

```{r}
# setup the folder and filenames to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

```{r}
# transcripts per sample
colSums(txi.kallisto$counts)
```
```{r}
# detected transcripts in at least 1 sample
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
# Filtering out transcripts with no leads
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]

# Filtering out transcripts with no change over samples
keep2 <- apply(kset.nonzero, 1, sd) > 0
x <- kset.nonzero[keep2,]
```

# PCA
```{r}
# computing principal components
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```
```{r}
# base R plot of PC1 and PC2
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```

> Q. Use ggplot to make a similar figure of PC1 vs PC2 and a seperate figure PC1 vs PC3 and PC2 vs PC3.

First we need to turn the data input into a dataframe:
```{r}
df <- as.data.frame(pca$x)
df$Condition <- c("control", "control", "treatment", "treatment")
```

```{r}
library(ggplot2)

# PC1 vs. PC2
ggplot(df, aes(PC1, PC2, col=Condition)) +
  geom_point() +
  labs(title = "PC1 vs PC2")
```

```{r}
# PC1 vs. PC3
ggplot(df, aes(PC1, PC3, col=Condition)) +
  geom_point() +
  labs(title = "PC1 vs PC3")
```

```{r}
# PC2 vs. PC3
ggplot(df, aes(PC2, PC3, col=Condition)) +
  geom_point() +
  labs(title = "PC2 vs PC3")
```

